### ISSUE TITLE
Docker 25.0.2 requires client version 1.12 or greater

### ISSUE THREAD

**Issue by snarkywolverine** [chabad360/cockpit-docker#1]
Cockpit version: 309
Cockpit-docker version: latest
Docker version: 25.0.2
OS: Debian 12

I'm doing a fresh install of everything, and wanted to manage docker with cockpit.  I was disappointed to learn that the plugin didn't work with the latest version of Docker -- instead I got an error that was something like:

Error 400 - The client version 1.12 is no longer supported; use 1.24 or higher.

I was able to workaround the issue by installing Docker 24.0.9, but would love to not have my brand new machine running outdated software.  Thanks!

**Comment by chabad360** [comment]
Hrm, that's a bit strange. I haven't updated this in a little while, but it's working fine for me. I'll be pushing an update later today, let me know if that helps.

Sorry for the delayed reply.

**Comment by chabad360** [comment]
Assuming this is fixed. Closing.
