### ISSUE TITLE
Deleting an image does not updates the UI

### ISSUE THREAD

**Issue by justalemon** [chabad360/cockpit-docker#6]
Cockpit version: 315-1
Cockpit-docker version: 15-1 from AUR
Docker version: 26.0.2, build 3c863ff8d3
OS: Arch Linux

When you delete an image, the UI does not updates showing that the image was deleted. If I manually refresh the page with F5, it will show the updated list of images.

Steps to reproduce

1. Go to Images and click Show Images
2. Click the 3 dots on an image
3. Select Delete
4. Click Delete tagged images
5. See that nothing in the UI has changed

or

1. Go to Images
2. Click the 3 dots to the right of Images
3. Select Prune unused images
4. Click Prune
5. See that nothing in the UI has changed

https://github.com/chabad360/cockpit-docker/assets/11861253/8129edcc-cbf1-407d-a323-3e238e09fb27

![image](https://github.com/chabad360/cockpit-docker/assets/11861253/41bdc63c-96e9-4375-a444-f01ae0769527)

**Comment by chabad360** [comment]
This is probably going to take me a little while to get to, as I'm on holiday now. Thank you for the report.

**Comment by chabad360** [comment]
Okay, I think I've fixed it (although for some reason it takes a few seconds to update).
