### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by mrepetto94** [chabad360/cockpit-docker#7]
I'm getting this error during installation.

```
make package-lock.json && NODE_ENV= ./build.js
make[1]: Entering directory '/home/marcorepettocertx/Documents/cockpit-podman'
tools/node-modules make_package_lock_json
make[1]: Leaving directory '/home/marcorepettocertx/Documents/cockpit-podman'
file:///home/marcorepettocertx/Documents/cockpit-podman/build.js:15
const esbuild = (await import(useWasm ? 'esbuild-wasm' : 'esbuild'));
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make: *** [Makefile:110: dist/manifest.json] Error 1
```

**Comment by chabad360** [comment]
How are you installing it? I'm not sure why you're running that command, `make install` should be enough.

**Comment by mrepetto94** [comment]
I'm using `make install` 
![image](https://github.com/chabad360/cockpit-docker/assets/119503933/dc5e2ef0-2576-4fbe-bfc7-398e4e1ab4b5)

**Comment by chabad360** [comment]
Ah, some quick searching leads me to believe you might be using an older version of Node (one without support for top-level async). But tbh, I'm not sure, but I'm pretty sure it's not a bug on my side (I've successfully built it in a number of scenarios) as this code is directly ported from cockpit-podman.

**Comment by mrepetto94** [comment]
Okey dokey, I'm using stock node provided in Ubuntu 22 LTS.

**Comment by chabad360** [comment]
Huh, that should be new enough. But I'm definitely out of my league here, so I don't think I can help further (esp. cause I can't reproduce the error).

Maybe ChatGPT can help?

**Comment by chabad360** [comment]
Oh! I take that back, I mis-read what you said. Google says the Ubuntu 22 LTS ships Node 12, which is too old. I believe you need at least Node 14.8.
